// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmzsfawyesnpeczfdqcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtenNmYXd5ZXNucGVjemZkcWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzQxMjIsImV4cCI6MjA2MDQ1MDEyMn0.0lFzWxslL2PpzIJVGmiaEoWXmUbdY1AOG0hvzGWtjUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);